---
- hosts: localhost
  tasks:
  - name: create VPC
    ec2_vpc_net:
      name: "{{ vpc_name }}"
      cidr_block: "{{ vpc_cidr }}"
      region: "{{ region }}"
      state: present
    register: vpc
    
  - name: set_var
    set_stats:
      data:
        vpc_id: "{{vpc.vpc.id}}"
  - debug:
      var: "{{vpc_id}}"
