---
- name: Create_EKS_Cluster
  hosts: 172.31.35.57
  
  tasks: 
  - name: run eks deploy images
    command: docker run docker.io/ruzyyu/eks_deploy:2 /bin/sh /scripts/eks_cluster_fargate/deploy_cluster.sh
