---
- name: Install nginx
  hosts: all

  tasks:
  - name: Install php-fpm and deps
    yum: name={{ item }} state=present
    with_items:
      - php
      - php-fpm
      - php-enchant
      - php-IDNA_Convert
      - php-mbstring
      - php-mysql
      - php-PHPMailer
      - php-process
      - php-simplepie
      - php-xml
